#!/usr/bin/env python3
import argparse
import json
import mimetypes
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import urlparse


class DebugHandler(SimpleHTTPRequestHandler):
    static_dir: Path
    diagnostics_path: Path

    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=str(self.static_dir), **kwargs)

    def end_headers(self):
        self.send_header("Cache-Control", "no-store")
        super().end_headers()

    def do_GET(self):
        path = urlparse(self.path).path
        if path == "/health":
            self._send_json({"ok": True})
            return
        if path == "/api/meta":
            if not self.diagnostics_path.is_file():
                self.send_error(404, "diagnostics JSONL not found")
                return
            stat = self.diagnostics_path.stat()
            self._send_json({
                "name": self.diagnostics_path.name,
                "path": str(self.diagnostics_path),
                "size": stat.st_size,
                "modified_ns": stat.st_mtime_ns,
            })
            return
        if path == "/api/diagnostics":
            self._send_diagnostics()
            return
        super().do_GET()

    def _send_json(self, value):
        payload = json.dumps(value, ensure_ascii=False).encode("utf-8")
        self.send_response(200)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(payload)))
        self.end_headers()
        self.wfile.write(payload)

    def _send_diagnostics(self):
        if not self.diagnostics_path.is_file():
            self.send_error(404, "diagnostics JSONL not found")
            return
        size = self.diagnostics_path.stat().st_size
        self.send_response(200)
        self.send_header("Content-Type", "application/x-ndjson; charset=utf-8")
        self.send_header("Content-Length", str(size))
        self.end_headers()
        with self.diagnostics_path.open("rb") as diagnostics:
            while chunk := diagnostics.read(1024 * 1024):
                self.wfile.write(chunk)

    def log_message(self, format_string, *args):
        print(f"[debug_3d] {self.address_string()} {format_string % args}")


def parse_args():
    parser = argparse.ArgumentParser(description="Serve the HFUT Three.js diagnostics viewer")
    parser.add_argument(
        "--diagnostics",
        default="/tmp/hfut_video_test.jsonl",
        help="diagnostics JSONL generated by video_test or bringup_sim",
    )
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8765)
    return parser.parse_args()


def main():
    args = parse_args()
    static_dir = Path(__file__).resolve().parent
    diagnostics_path = Path(args.diagnostics).expanduser().resolve()
    mimetypes.add_type("text/javascript", ".js")
    DebugHandler.static_dir = static_dir
    DebugHandler.diagnostics_path = diagnostics_path
    server = ThreadingHTTPServer((args.host, args.port), DebugHandler)
    print(f"[debug_3d] http://{args.host}:{args.port}")
    print(f"[debug_3d] diagnostics={diagnostics_path}")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()


if __name__ == "__main__":
    main()
